### ISSUE TITLE
Quick tutorial for custom datasets?

### ISSUE THREAD

**Issue by marvision-ai** [dusty-nv/pytorch-segmentation#3]
Hi @dusty-nv ,

Thanks for all the work you do on the inference repo. I realized you are using this repo to provide the models for the segmentation. 

I was wondering if there was a quick and simple tutorial somewhere that explains the best way to use this repo in order to train on custom datasets and then use with the jetsoninfernce libs.

Thanks!

**Comment by dusty-nv** [comment]
Hi mbufi, this was forked from the torchvision examples:   https://github.com/pytorch/vision/blob/master/references/segmentation/README.md

I added support for fcn-resnet18, fcn-resnet34, and fcn-resnet50, and added support for a bunch of datasets.  I do plan to make a tutorial around this for Hello AI World, hopefully in not too long.  I need to finish the one for object detection first (pytorch-ssd).

Note that if you want to use this, see my fork of torchvision, the 0.3.0 branch.  It is there that there is fcn-resnet18, ect.  I need to move these into this repo from torchvision fork before deploying the tutorial.
________________________________

**Comment by marvision-ai** [comment]
@dusty-nv Thats great news! Thank you for that. I would love to utilize more of the repo you have been working on. 

I am excited to see what you bring. 
Cheers

**Comment by donkorechi** [comment]
Hi @dusty-nv,

Is the possibility of quick tutorial for custom dataset still in consideration?
I loved the tutorial that was made for Obstacle Detection. It would be nice if the same is done for segmentation.
Thanks

**Comment by dusty-nv** [comment]
Hi @donkorechi, for now I would refer you to this tutorial on training segmentation models that work with jetson-inference library:  https://www.highvoltagecode.com/post/edge-ai-semantic-segmentation-on-nvidia-jetson
